name: Push to Test Firebase
on:
  push:
    branches:
    - test
jobs:
  main:
    name: Push to Test Firebase
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: TestCalNourish