name: Push Master Branch to Master Firebase Project
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy -m \"${{ github.event.head_commit.message }} @${{ github.event.head_commit.author.name }}\" --except functions:production
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        PROJECT_ID: production
